version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY:-DUMMY_API_KEY_12345}
      - PORT=8080
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
